# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sentia-generators}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Cindric"]
  s.date = %q{2010-03-16}
  s.description = %q{A collectio of generators that we use on our projects. Only supports the way we doing things for example only generates haml views and not erb.}
  s.email = %q{michael.cindric@sentia.com.au}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/sentia-generators.rb",
     "rails_generators/sentia_authentication/USAGE",
     "rails_generators/sentia_authentication/sentia_authentication_generator.rb",
     "rails_generators/sentia_authentication/templates/users/_form.html.haml",
     "rails_generators/sentia_authentication/templates/users/edit.html.haml",
     "rails_generators/sentia_authentication/templates/users/new.html.haml",
     "rails_generators/sentia_authentication/templates/users/show.html.haml",
     "rails_generators/sentia_layout/USEAGE",
     "rails_generators/sentia_layout/sentia_layout_generator.rb",
     "rails_generators/sentia_layout/templates/layout.html.haml",
     "rails_generators/sentia_layout/templates/stylesheet.sass",
     "script/console",
     "script/destroy",
     "script/generate",
     "sentia-generators.gemspec",
     "test/helper.rb",
     "test/test_sentia-generators.rb"
  ]
  s.homepage = %q{http://github.com/Sentia/sentia-generators}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A collection of useful Rails generator scripts that we use on our projects}
  s.test_files = [
    "test/helper.rb",
     "test/test_sentia-generators.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<haml>, [">= 2.2.9"])
    else
      s.add_dependency(%q<haml>, [">= 2.2.9"])
    end
  else
    s.add_dependency(%q<haml>, [">= 2.2.9"])
  end
end

